version: "3.8"
name: my_app

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: nana1123!
      MYSQL_DATABASE: testdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
      MYSQL_CHARSET: utf8mb4
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: db 
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
      MYSQL_DATABASE: testdb
      MYSQL_PORT: 3306
      FLASK_APP: main.py
      FLASK_ENV: development
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data:
